concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true
jobs:
  lint:
    name: Lint workflows
    permissions:
      contents: read # required to check out the repository
    uses: praw-dev/.github/.github/workflows/lint.yml@70f242e0b52b68314601cf66674b63bc70105e71 # test fix-lint-concurrency
name: Lint workflows
on:
  pull_request:
  push:
    branches: ["main"]
permissions: {}
